const NO2LOW_CONGESTION = 'NO2LOW_CONGESTION';
const MODERATE_CONGESTION = 'MODERATE_CONGESTION';
const SEVERE_CONGESTION = 'SEVERE_CONGESTION';

module.exports = {
  NO2LOW_CONGESTION,
  MODERATE_CONGESTION,
  SEVERE_CONGESTION
};
