const LOTTR = 'LOTTR';
const TTTR = 'TTTR';
// const PHED = 'PHED';
const PERCENT_BINS_REPORTING = 'PERCENT_BINS_REPORTING';
const SUMMARY_STATISTICS = 'SUMMARY_STATISTICS'

module.exports = {
  LOTTR,
  TTTR,
  PERCENT_BINS_REPORTING,
  SUMMARY_STATISTICS
};
